#Check this doc on how to create a TLS secret.
#https://kubernetes.github.io/ingress-nginx/user-guide/tls/
apiVersion: v1
data:
  tls.crt: yourtls.crtfilecontents go here, encoded in base64 
  tls.key: yourtls.keyfilecontents fo here, encoded in base64
kind: Secret
metadata:
  name: loki-tls
type: kubernetes.io/tls
