apiVersion: v1
kind: Secret
metadata:
  name: loki-postgres-configuration
  namespace: awx 
stringData:
  host: "loki"
  port: "5432"
  database: "awx"
  username: "awx"
  password: "yoursupersecretpasswordinplaintext"
  sslmode: prefer
  type: unmanaged
type: Opaque
