apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: loki
  namespace: awx
spec:
  service_type: NodePort
  nodeport_port: 30080
  ingress_type: ingress 
  hostname: ansible.aimcorp.co.uk
  ingress_tls_secret: loki-tls
  task_privileged: false 
  auto_upgrade: true
  postgres_configuration_secret: loki-postgres-configuration 
  no_log: "false"

 #######
 # this section is for kerberos authentication.
 # I have included a krb5.yaml file with a complete configuration. 
 # You will need to update the domain_realm section and the default_realm with your own organization's
 #  set_self_labels: false
 # no_log: 'false'
 # extra_volumes: |
 #         - name: krb5
 #           configMap:
 #             defaultMode: 420
 #             items:
 #               - key: krb5.conf
 #                 path: krb5.conf
 #             name: krb5
 #
 # task_extra_volume_mounts: |
 #         - name: krb5
 #           mountPath: /etc/krb5.conf
 #           subPath: krb5.conf
 # ee_extra_volume_mounts: |
 #         - name: krb5
 #           mountPath: /etc/krb5.conf
 #           subPath: krb5.conf

